# Generated by Django 5.2 on 2025-04-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.URLField(blank=True, null=True)),
                ('small_art', models.URLField(blank=True, null=True)),
                ('wide_art', models.URLField(blank=True, null=True)),
                ('large_art', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('puuid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=5)),
                ('recent_matches', models.JSONField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.playercard')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.playertitle')),
            ],
        ),
    ]
