# Generated by Django 5.1.6 on 2025-04-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAbility',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('displayIcon', models.URLField(blank=True, null=True)),
                ('listViewIcon', models.URLField(blank=True, null=True)),
                ('listViewIconTall', models.URLField(blank=True, null=True)),
                ('splash', models.URLField(blank=True, null=True)),
                ('stylizedBackgroundImage', models.URLField(blank=True, null=True)),
                ('premierBackgroundImage', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.URLField(blank=True, null=True)),
                ('small_art', models.URLField(blank=True, null=True)),
                ('wide_art', models.URLField(blank=True, null=True)),
                ('large_art', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('developerName', models.CharField(max_length=120)),
                ('icon', models.URLField(blank=True, null=True)),
                ('icon_small', models.URLField(blank=True, null=True)),
                ('bust_image', models.URLField(blank=True, null=True)),
                ('full_image', models.URLField(blank=True, null=True)),
                ('full_image_v2', models.URLField(blank=True, null=True)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('ability1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability1', to='web.agentability')),
                ('ability2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability2', to='web.agentability')),
                ('grenade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grenade', to='web.agentability')),
                ('passive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive', to='web.agentability')),
                ('ultimate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate', to='web.agentability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.agentrole')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('json_data', models.JSONField()),
                ('red_result', models.IntegerField()),
                ('blue_result', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('game_duration', models.TimeField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='web.map')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('puuid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=5)),
                ('recent_matches', models.JSONField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.playercard')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.playertitle')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('roundResult', models.CharField(blank=True, max_length=120, null=True)),
                ('roundCeremony', models.CharField(blank=True, max_length=120, null=True)),
                ('roundResultCode', models.CharField(blank=True, max_length=120, null=True)),
                ('winner_team', models.CharField(max_length=120)),
                ('winnerSide', models.CharField(max_length=120)),
                ('loser', models.CharField(max_length=120)),
                ('loserSide', models.CharField(max_length=120)),
                ('plantRoundTime', models.CharField(blank=True, max_length=120, null=True)),
                ('defuseRoundTime', models.CharField(blank=True, max_length=120, null=True)),
                ('plantSite', models.CharField(blank=True, max_length=1, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='web.match')),
                ('bombDefuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_defused', to='web.user')),
                ('bombPlanter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_planted', to='web.user')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=120)),
                ('hasWon', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches', to='web.agent')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_matches', to='web.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='web.user')),
            ],
        ),
    ]
